
<?php echo $this->tag->form("vkresources/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("vkresources", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create vkresources</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="vk_id">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="vk_id">Vk</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("vk_id", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="vk_id">URL</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("url", "size" => 30)) ?>
        </td>
    </tr>




    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
